name: PermissionsSql
main: com.nijikokun.bukkit.Permissions.PermissionsSql
version: 1.1
author: rcjrrjcr
website: www.theyeticave.net
description: >
             Provides SQL functionality for Permissions
