name: PermissionsSql
main: com.nijikokun.bukkit.Permissions.PermissionsSql
version: 1.3
author: rcjrrjcr
website: www.theyeticave.net
depend:
    - Permissions
description: >
             Provides SQL functionality for Permissions